#!/usr/bin/env ruby
# frozen_string_literal: true

ROOT = File.dirname(File.realpath(__FILE__))
ENV["BUNDLE_GEMFILE"] ||= File.join(ROOT, "Gemfile")

require "bundler/setup"
require "dotenv"

Dotenv.load(File.join(ROOT, ".env"))
$LOAD_PATH.unshift(File.join(ROOT, "lib"))

require "todos/cli"

exit(Todos::CLI.run(ARGV))
