#!/usr/bin/env ruby
# frozen_string_literal: true

ROOT = File.dirname(File.realpath(__FILE__))
env_file = File.join(ROOT, ".env")
File.foreach(env_file, chomp: true) do |line|
  key, value = line.split("=", 2)
  ENV[key] ||= value if key && value && !key.empty? && !key.start_with?("#")
end if File.file?(env_file)

$LOAD_PATH.unshift(File.join(ROOT, "lib"))

require "todos/cli"

exit(Todos::CLI.run(ARGV))
